# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['questions', 'foo', 'display_quiz', 'say_hello']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/00_core.ipynb 5
from IPython.display import Markdown, display

# Define the questions and answers
questions = [
    {
        "question": "What is the capital of France?",
        "options": ["Paris", "London", "Berlin", "Rome"],
        "answer": "Paris"
    },
    {
        "question": "Which planet is known as the Red Planet?",
        "options": ["Venus", "Mars", "Jupiter", "Saturn"],
        "answer": "Mars"
    },
    {
        "question": "Who painted the Mona Lisa?",
        "options": ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"],
        "answer": "Leonardo da Vinci"
    }
]

# Function to display the multiple-choice quiz
def display_quiz(questions):
    for i, question in enumerate(questions):
        print(f"Question {i+1}: {question['question']}")
        for j, option in enumerate(question['options']):
            print(f"{j+1}. {option}")
        print()

# Call the function to display the quiz
display_quiz(questions)

# %% ../nbs/00_core.ipynb 6
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
